sage_agent_controller:
  module: "src.agents.instance.sage_agent_controller.SAGEAgentController"
  parameters:
    language_model: "Fill the parameter 'language_model_name' in assignment config."
    inference_config_dict: {}
